// Migrated from packages/shared/src/hooks/useSpiritualPractices.ts
// Prefer importing from '@cosmichub/hooks'.
import { useState, useCallback, useEffect, useRef } from 'react';
import type {
  SpiritualPracticeLevel as SpiritualLevel,
  PracticeType,
  SafetyStatus,
  PathworkingSessionRequest,
  PathworkingResponse,
  TarotMeditationRequest,
  TarotMeditationResponse,
  HebrewLetterRequest,
  HebrewLetterResponse,
  DailyRoutineRequest,
  DailyRoutineResponse,
  PracticeReadinessRequest,
  PracticeReadinessAssessment,
  SafetyCheckRequest,
  SafetyCheckResponse,
  StartSessionRequest,
  SessionStartResponse,
  CompleteSessionRequest,
  SessionCompletionResponse,
  SpiritualPracticeUserProgress as UserProgress,
  TreePathsResource,
  HebrewLettersResource,
  UseSpiritualPracticesResult,
} from '@cosmichub/types';

const SPIRITUAL_PRACTICES_API_BASE = '/api/spiritual/practices';

class SpiritualPracticeError extends Error { constructor(message: string, public code?: string, public data?: unknown){ super(message); this.name='SpiritualPracticeError'; } }

class SpiritualPracticesAPI { private static async request<T>(endpoint: string, options: RequestInit = {}): Promise<T> { const url = `${SPIRITUAL_PRACTICES_API_BASE}${endpoint}`; const isErr = (v: unknown): v is { message?: unknown; code?: unknown } => typeof v === 'object' && v !== null; try { const response = await fetch(url,{ headers:{'Content-Type':'application/json', ...(options.headers ?? {})}, ...options }); if(!response.ok){ let parsed: unknown=null; try { parsed=await response.json(); } catch { /* ignore body parse error */ } const message = isErr(parsed) && typeof parsed.message==='string'? parsed.message: `Request failed with status ${response.status}`; const code = isErr(parsed) && typeof parsed.code==='string'? parsed.code: undefined; throw new SpiritualPracticeError(message, code, parsed ?? undefined);} let data: unknown; try { data=await response.json(); } catch { throw new SpiritualPracticeError('Invalid JSON response from server'); } return data as T; } catch(err){ if(err instanceof SpiritualPracticeError) throw err; const message = err instanceof Error? err.message: 'Unknown error'; throw new SpiritualPracticeError(`Network error: ${message}`);} } static assessReadiness(r: PracticeReadinessRequest){ return this.request<{assessment:PracticeReadinessAssessment}>('/assess-readiness',{method:'POST',body:JSON.stringify(r)}).then(res=>res.assessment);} static generatePathworking(r: PathworkingSessionRequest){ return this.request<PathworkingResponse>('/pathworking/generate',{method:'POST',body:JSON.stringify(r)});} static generateTarotMeditation(r: TarotMeditationRequest){ return this.request<TarotMeditationResponse>('/tarot/meditation',{method:'POST',body:JSON.stringify(r)});} static generateHebrewSession(r: HebrewLetterRequest){ return this.request<HebrewLetterResponse>('/hebrew/contemplation',{method:'POST',body:JSON.stringify(r)});} static generateDailyRoutine(r: DailyRoutineRequest){ return this.request<DailyRoutineResponse>('/daily-routine/generate',{method:'POST',body:JSON.stringify(r)});} static performSafetyCheck(r: SafetyCheckRequest){ return this.request<SafetyCheckResponse>('/safety-check',{method:'POST',body:JSON.stringify(r)});} static startSession(r: StartSessionRequest){ return this.request<SessionStartResponse>('/session/start',{method:'POST',body:JSON.stringify(r)});} static completeSession(id:string,r:CompleteSessionRequest){ return this.request<SessionCompletionResponse>(`/session/${id}/complete`,{method:'POST',body:JSON.stringify(r)});} static getProgress(userId:string){ return this.request<UserProgress>(`/progress/${userId}`);} static getTreePaths(){ return this.request<TreePathsResource>('/resources/paths'); } static getHebrewLetters(){ return this.request<HebrewLettersResource>('/resources/hebrew-letters'); } }

export function useSpiritualPractices(): UseSpiritualPracticesResult { const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [activeSession,setActiveSession]=useState<SessionStartResponse|null>(null); const clearError=useCallback(()=>setError(null),[]); const withErrorHandling=useCallback(async <T>(op:()=>Promise<T>):Promise<T>=>{ try { clearError(); setLoading(true); return await op(); } catch(err){ const message = err instanceof SpiritualPracticeError? err.message: 'An unexpected error occurred'; setError(message); throw err; } finally { setLoading(false);} },[clearError]); const generatePathworking=useCallback((r:PathworkingSessionRequest)=>withErrorHandling(()=>SpiritualPracticesAPI.generatePathworking(r)),[withErrorHandling]); const generateTarotMeditation=useCallback((r:TarotMeditationRequest)=>withErrorHandling(()=>SpiritualPracticesAPI.generateTarotMeditation(r)),[withErrorHandling]); const generateHebrewSession=useCallback((r:HebrewLetterRequest)=>withErrorHandling(()=>SpiritualPracticesAPI.generateHebrewSession(r)),[withErrorHandling]); const generateDailyRoutine=useCallback((r:DailyRoutineRequest)=>withErrorHandling(()=>SpiritualPracticesAPI.generateDailyRoutine(r)),[withErrorHandling]); const assessReadiness=useCallback((r:PracticeReadinessRequest)=>withErrorHandling(()=>SpiritualPracticesAPI.assessReadiness(r)),[withErrorHandling]); const performSafetyCheck=useCallback((r:SafetyCheckRequest)=>withErrorHandling(()=>SpiritualPracticesAPI.performSafetyCheck(r)),[withErrorHandling]); const startSession=useCallback(async (r:StartSessionRequest)=>{ const res= await withErrorHandling(()=>SpiritualPracticesAPI.startSession(r)); setActiveSession(res); return res; },[withErrorHandling]); const completeSession=useCallback(async (id:string,r:CompleteSessionRequest)=>{ const res= await withErrorHandling(()=>SpiritualPracticesAPI.completeSession(id,r)); setActiveSession(null); return res; },[withErrorHandling]); const getProgress=useCallback((userId:string)=>withErrorHandling(()=>SpiritualPracticesAPI.getProgress(userId)),[withErrorHandling]); const getTreePaths=useCallback(()=>withErrorHandling(()=>SpiritualPracticesAPI.getTreePaths()),[withErrorHandling]); const getHebrewLetters=useCallback(()=>withErrorHandling(()=>SpiritualPracticesAPI.getHebrewLetters()),[withErrorHandling]); return { generatePathworking, generateTarotMeditation, generateHebrewSession, generateDailyRoutine, assessReadiness, performSafetyCheck, startSession, completeSession, getProgress, getTreePaths, getHebrewLetters, loading, error, activeSession }; }

export function usePathworking(){ const [pathworkingSession,setPathworkingSession]=useState<PathworkingResponse|null>(null); const [currentPath,setCurrentPath]=useState<number|null>(null); const [sessionProgress,setSessionProgress]=useState<{phase:'preparation'|'journey'|'integration'|'complete'; timeRemaining?:number;}>({phase:'preparation'}); const { generatePathworking,startSession, completeSession: _completeSession, loading,error } = useSpiritualPractices(); const createPathworkingSession=useCallback(async (pathNumber:number,userLevel:SpiritualLevel,duration=20)=>{ const response= await generatePathworking({ path_number: pathNumber, user_level: userLevel, session_duration: duration }); setPathworkingSession(response); setCurrentPath(pathNumber); setSessionProgress({phase:'preparation'}); return response; },[generatePathworking]); const startPathworking=useCallback(async (level:SpiritualLevel)=>{ if(!pathworkingSession) throw new Error('No pathworking session available'); const sessionResponse= await startSession({ practice_type:'pathworking', session_content: (pathworkingSession.data as unknown as Record<string, unknown>) ?? {}, level, estimated_duration: pathworkingSession.estimated_duration }); setSessionProgress({ phase:'journey', timeRemaining: pathworkingSession.estimated_duration }); return sessionResponse; },[pathworkingSession,startSession]); const completePathworking=useCallback(async (sessionId:string,insights:string[],adverseEffects?:string[])=>{ const response= await _completeSession(sessionId,{ insights, adverse_effects: adverseEffects, completion_quality:'full' }); setSessionProgress({phase:'complete'}); return response; },[_completeSession]); const resetPathworking=useCallback(()=>{ setPathworkingSession(null); setCurrentPath(null); setSessionProgress({phase:'preparation'}); },[]); return { pathworkingSession, currentPath, sessionProgress, loading, error, createPathworkingSession, startPathworking, completePathworking, resetPathworking }; }

export function useTarotMeditation(){ const [tarotSession,setTarotSession]=useState<TarotMeditationResponse|null>(null); const [currentCard,setCurrentCard]=useState<string|null>(null); const [dailyCard,setDailyCard]=useState<{card:string; date:string; insights:string[];}|null>(null); const { generateTarotMeditation,startSession, completeSession: _unusedCompleteSessionTarot, loading,error } = useSpiritualPractices(); const createTarotMeditation=useCallback(async (type:'daily'|'journey'|'correspondence', userLevel:SpiritualLevel, cardPreference?:string)=>{ const response= await generateTarotMeditation({ meditation_type:type, user_level:userLevel, card_preference: cardPreference }); setTarotSession(response); setCurrentCard(response.data?.card ?? null); if(type==='daily'){ setDailyCard({ card: response.data?.card ?? '', date: new Date().toDateString(), insights: [] }); } return response; },[generateTarotMeditation]); const startTarotMeditation=useCallback(async (level:SpiritualLevel)=>{ if(!tarotSession) throw new Error('No Tarot session available'); return startSession({ practice_type:'tarot_meditation', session_content: (tarotSession.data as unknown as Record<string, unknown>) ?? {}, level, estimated_duration: tarotSession.data?.duration_minutes ?? 15 }); },[tarotSession,startSession]); const addDailyInsight=useCallback((insight:string)=>{ setDailyCard(prev=> prev? { ...prev, insights: [...prev.insights,insight]}: prev); },[]); const getDailyCard=useCallback(async (userLevel:SpiritualLevel)=>{ const today= new Date().toDateString(); if(dailyCard && dailyCard.date===today) return dailyCard; await createTarotMeditation('daily', userLevel); return dailyCard; },[dailyCard,createTarotMeditation]); return { tarotSession, currentCard, dailyCard, loading, error, createTarotMeditation, startTarotMeditation, getDailyCard, addDailyInsight }; }

export function useHebrewLetters(){ const [hebrewSession,setHebrewSession]=useState<HebrewLetterResponse|null>(null); const [currentLetter,setCurrentLetter]=useState<string|null>(null); const [studyProgress,setStudyProgress]=useState<{lettersStudied:string[]; currentStreak:number; totalSessions:number;}>({ lettersStudied:[], currentStreak:0, totalSessions:0}); const { generateHebrewSession,startSession, completeSession, getHebrewLetters, loading,error } = useSpiritualPractices(); const createHebrewSession=useCallback(async (letter:string,userLevel:SpiritualLevel,includeGematria=true)=>{ const response= await generateHebrewSession({ letter, user_level:userLevel, include_gematria: includeGematria }); setHebrewSession(response); setCurrentLetter(letter); return response; },[generateHebrewSession]); const startHebrewSession=useCallback(async (level:SpiritualLevel)=>{ if(!hebrewSession) throw new Error('No Hebrew session available'); return startSession({ practice_type:'hebrew_contemplation', session_content: (hebrewSession.data as unknown as Record<string, unknown>) ?? {}, level, estimated_duration: hebrewSession.data?.meditation_duration ?? 15 }); },[hebrewSession,startSession]); const completeHebrewSession=useCallback(async (sessionId:string,insights:string[],letter:string)=>{ const response= await completeSession(sessionId,{ insights, completion_quality:'full' }); setStudyProgress(prev=>{ const newLetters = prev.lettersStudied.includes(letter)? prev.lettersStudied: [...prev.lettersStudied,letter]; return { lettersStudied: newLetters, currentStreak: prev.currentStreak+1, totalSessions: prev.totalSessions+1 }; }); return response; },[completeSession]); const getNextLetter=useCallback(async (_userLevel:SpiritualLevel)=>{ const letters= await getHebrewLetters(); const keys= Object.keys(letters.letters); const next= keys.find(l=> !studyProgress.lettersStudied.includes(l)); return next ?? keys[0]; },[getHebrewLetters,studyProgress.lettersStudied]); return { hebrewSession, currentLetter, studyProgress, loading, error, createHebrewSession, startHebrewSession, completeHebrewSession, getNextLetter }; }

export function useDailyRoutine(){ const [dailyRoutine,setDailyRoutine]=useState<DailyRoutineResponse|null>(null); const [todayProgress,setTodayProgress]=useState<{ morningComplete:boolean; eveningComplete:boolean; insightsRecorded:number; currentStreak:number;}>({ morningComplete:false, eveningComplete:false, insightsRecorded:0, currentStreak:0 }); const { generateDailyRoutine, loading,error } = useSpiritualPractices(); const createDailyRoutine=useCallback(async (userLevel:SpiritualLevel, availableTime:number, spiritualGoals:string[] = [], focusAreas:string[] = [])=>{ const response= await generateDailyRoutine({ user_level:userLevel, available_time: availableTime, spiritual_goals: spiritualGoals, focus_areas: focusAreas }); setDailyRoutine(response); return response; },[generateDailyRoutine]); const completeMorningPractice=useCallback((insights:string[] = [])=>{ setTodayProgress(prev=>({...prev,morningComplete:true,insightsRecorded: prev.insightsRecorded+insights.length })); },[]); const completeEveningPractice=useCallback((insights:string[]=[])=>{ setTodayProgress(prev=>{ const both= prev.morningComplete; return { ...prev, eveningComplete:true, insightsRecorded: prev.insightsRecorded+insights.length, currentStreak: both? prev.currentStreak+1: prev.currentStreak }; }); },[]); const resetDailyProgress=useCallback(()=>{ setTodayProgress(prev=>({ morningComplete:false, eveningComplete:false, insightsRecorded:0, currentStreak: prev.currentStreak })); },[]); const getDailyCompletionPercentage=useCallback(()=>{ const { morningComplete, eveningComplete, insightsRecorded } = todayProgress; let pct=0; if(morningComplete) pct+=40; if(eveningComplete) pct+=40; if(insightsRecorded>0) pct+=20; return pct; },[todayProgress]); return { dailyRoutine, todayProgress, loading, error, createDailyRoutine, completeMorningPractice, completeEveningPractice, resetDailyProgress, getDailyCompletionPercentage }; }

export function usePracticeSafety(){ const [safetyStatus,setSafetyStatus]=useState<SafetyStatus>('cleared'); const [safetyAlerts,setSafetyAlerts]=useState<string[]>([]); const [emergencyMode,setEmergencyMode]=useState(false); const { performSafetyCheck, loading,error } = useSpiritualPractices(); const checkSafety=useCallback(async (practiceType:PracticeType, level:SpiritualLevel, currentState:{ grounded:boolean; recentAdverseEffects:string[]; sleepQuality:'good'|'fair'|'poor'; stressLevel:number; })=>{ try { const response = await performSafetyCheck({ practice_session:{ type: practiceType, level, duration:20, preparation_complete:false, protection_invoked:false }, current_state:{ grounded: currentState.grounded, recent_adverse_effects: currentState.recentAdverseEffects, sleep_quality: currentState.sleepQuality, stress_level: currentState.stressLevel } }); const result = response.data; if(result){ setSafetyStatus(result.safe_to_proceed? 'cleared':'restricted'); setSafetyAlerts(result.warnings || []);} return response; } catch(err){ console.error('Safety check failed:', err); setSafetyStatus('restricted'); setSafetyAlerts(['Safety check failed - practice not recommended']); throw err; } },[performSafetyCheck]); const triggerEmergency=useCallback((reason:string)=>{ setEmergencyMode(true); setSafetyStatus('emergency'); setSafetyAlerts(prev=>[...prev,`Emergency: ${reason}`]); console.warn('SPIRITUAL PRACTICE EMERGENCY TRIGGERED:', reason); },[]); const clearEmergency=useCallback(()=>{ setEmergencyMode(false); setSafetyStatus('cleared'); setSafetyAlerts([]); },[]); const addSafetyAlert=useCallback((alert:string)=>{ setSafetyAlerts(prev=>[...prev,alert]); if(safetyStatus==='cleared') setSafetyStatus('caution'); },[safetyStatus]); const clearAlerts=useCallback(()=>{ setSafetyAlerts([]); if(!emergencyMode) setSafetyStatus('cleared'); },[emergencyMode]); return { safetyStatus, safetyAlerts, emergencyMode, loading, error, checkSafety, triggerEmergency, clearEmergency, addSafetyAlert, clearAlerts }; }

export function useSessionTimeout(timeoutMinutes=60){ const timeoutRef = useRef<ReturnType<typeof setTimeout>>(); const [timeRemaining,setTimeRemaining]=useState<number|null>(null); const startTimeout=useCallback((onTimeout:()=>void)=>{ if(timeoutRef.current) clearTimeout(timeoutRef.current); const timeoutMs = timeoutMinutes*60*1000; setTimeRemaining(timeoutMinutes*60); timeoutRef.current = setTimeout(()=>{ onTimeout(); setTimeRemaining(null); }, timeoutMs); const interval = setInterval(()=>{ setTimeRemaining(prev=>{ if(prev===null || prev<=60){ clearInterval(interval); return null;} return prev-60; }); },60000); },[timeoutMinutes]); const clearSessionTimeout=useCallback(()=>{ if(timeoutRef.current){ clearTimeout(timeoutRef.current); timeoutRef.current=undefined;} setTimeRemaining(null); },[]); useEffect(()=>()=>{ if(timeoutRef.current) clearTimeout(timeoutRef.current); },[]); return { timeRemaining, startTimeout, clearTimeout: clearSessionTimeout }; }

export { SpiritualPracticesAPI, SpiritualPracticeError };
