repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        files: ^backend/
        language_version: python3
        args: [--line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^backend/
        args: [--profile=black, --line-length=88]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^backend/
        args: [--select=F401,F601,F811,F821,F822,F823,F824,E722]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: ^apps/astro/src/.*\.(ts|tsx|js|jsx|json|css|md)$
        exclude: ^apps/astro/src/.*\.d\.ts$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        files: ^apps/astro/src/.*\.(ts|tsx)$
        args: [--max-warnings=0, --format=compact]
        additional_dependencies:
          - eslint@^8.44.0
          - "@typescript-eslint/eslint-plugin@^6.0.0"
          - "@typescript-eslint/parser@^6.0.0"
