import type { AstrologyChart } from '@cosmichub/types';

// Sample chart data extracted from ChartDisplay (used when no valid data is provided)
export const sampleChartData: AstrologyChart = {
  planets: {
    sun: {
      name: 'Sun',
      sign: 'gemini',
      degree: 28.42,
      position: 88.42,
      house: 10,
      retrograde: false,
      speed: 1.02,
      aspects: [],
    },
    moon: {
      name: 'Moon',
      sign: 'pisces',
      degree: 15.18,
      position: 345.18,
      house: 7,
      retrograde: false,
      speed: 13.18,
      aspects: [],
    },
    mercury: {
      name: 'Mercury',
      sign: 'gemini',
      degree: 22.35,
      position: 82.35,
      house: 10,
      retrograde: false,
      speed: 0.87,
      aspects: [],
    },
    venus: {
      name: 'Venus',
      sign: 'taurus',
      degree: 8.56,
      position: 38.56,
      house: 9,
      retrograde: false,
      speed: 1.21,
      aspects: [],
    },
    mars: {
      name: 'Mars',
      sign: 'virgo',
      degree: 12.23,
      position: 162.23,
      house: 1,
      retrograde: false,
      speed: 0.63,
      aspects: [],
    },
    jupiter: {
      name: 'Jupiter',
      sign: 'cancer',
      degree: 25.47,
      position: 115.47,
      house: 11,
      retrograde: false,
      speed: 0.11,
      aspects: [],
    },
  },
  houses: [
    {
      number: 1,
      cusp: 155.23,
      sign: 'virgo',
      degree: 155.23,
      ruler: 'mercury',
      size: 33.22,
    },
    {
      number: 2,
      cusp: 188.45,
      sign: 'libra',
      degree: 188.45,
      ruler: 'venus',
      size: 33.73,
    },
    {
      number: 3,
      cusp: 222.18,
      sign: 'scorpio',
      degree: 222.18,
      ruler: 'mars',
      size: 45.97,
    },
    {
      number: 4,
      cusp: 268.15,
      sign: 'sagittarius',
      degree: 268.15,
      ruler: 'jupiter',
      size: 17.18,
    },
    {
      number: 5,
      cusp: 285.33,
      sign: 'capricorn',
      degree: 285.33,
      ruler: 'saturn',
      size: 37.11,
    },
    {
      number: 6,
      cusp: 322.44,
      sign: 'aquarius',
      degree: 322.44,
      ruler: 'uranus',
      size: 12.79,
    },
    {
      number: 7,
      cusp: 335.23,
      sign: 'pisces',
      degree: 335.23,
      ruler: 'neptune',
      size: 33.22,
    },
    {
      number: 8,
      cusp: 8.45,
      sign: 'aries',
      degree: 8.45,
      ruler: 'mars',
      size: 33.73,
    },
    {
      number: 9,
      cusp: 42.18,
      sign: 'taurus',
      degree: 42.18,
      ruler: 'venus',
      size: 45.97,
    },
    {
      number: 10,
      cusp: 88.15,
      sign: 'gemini',
      degree: 88.15,
      ruler: 'mercury',
      size: 17.18,
    },
    {
      number: 11,
      cusp: 105.33,
      sign: 'cancer',
      degree: 105.33,
      ruler: 'moon',
      size: 37.11,
    },
    {
      number: 12,
      cusp: 142.44,
      sign: 'leo',
      degree: 142.44,
      ruler: 'sun',
      size: 12.79,
    },
  ],
  aspects: [
    {
      aspect_type: 'trine',
      planet1: 'sun',
      planet2: 'moon',
      orb: 2.5,
      applying: true,
      exact: false,
      power: 0.8,
      aspect_angle: 120,
    },
    {
      aspect_type: 'square',
      planet1: 'sun',
      planet2: 'mars',
      orb: 1.8,
      applying: true,
      exact: false,
      power: 0.9,
      aspect_angle: 90,
    },
    {
      aspect_type: 'trine',
      planet1: 'venus',
      planet2: 'jupiter',
      orb: 3.2,
      applying: false,
      exact: false,
      power: 0.7,
      aspect_angle: 120,
    },
    {
      aspect_type: 'sextile',
      planet1: 'moon',
      planet2: 'venus',
      orb: 0.9,
      applying: false,
      exact: true,
      power: 1.0,
      aspect_angle: 60,
    },
  ],
  asteroids: {
    chiron: { 
      name: 'Chiron', 
      sign: 'cancer', 
      degree: 18.45, 
      house: 11, 
      position: 108.45, 
      retrograde: false, 
      speed: 0.05 
    },
    lilith: { 
      name: 'Lilith', 
      sign: 'scorpio', 
      degree: 29.12, 
      house: 3, 
      position: 239.12, 
      retrograde: false, 
      speed: 0.11 
    },
    ceres: { 
      name: 'Ceres', 
      sign: 'leo', 
      degree: 6.38, 
      house: 12, 
      position: 126.38, 
      retrograde: false, 
      speed: 0.33 
    },
  },
  angles: {
    ascendant: 155.23,
    midheaven: 88.15,
    descendant: 335.23,
    imumcoeli: 268.15,
    vertex: 45.67,
    part_of_fortune: 234.89,
  },
  latitude: 40.7128,
  longitude: -74.0060,
  timezone: 'America/New_York',
  julian_day: 2459945.5,
  house_system: 'placidus',
};
