name: Storybook CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Storybook
        working-directory: apps/astro
        run: pnpm run build-storybook
      - name: Upload static Storybook
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: apps/astro/storybook-static
