# Prometheus Configuration for CosmicHub
# This configuration works with the alert rules defined in alert-rules.yml
# Part of OBS-010: Prometheus alert rules setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'cosmichub-production'
    replica: 'prometheus-1'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules files
rule_files:
  - "alert-rules.yml"

# Scrape configuration
scrape_configs:
  # CosmicHub Backend API
  - job_name: 'cosmichub-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    # Add labels for better organization
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'cosmichub-backend'
    metric_relabel_configs:
      # Ensure consistent labeling
      - source_labels: [__name__]
        regex: 'http_.*'
        target_label: component
        replacement: 'api'

  # Ephemeris Calculation Service
  - job_name: 'ephemeris-server'
    static_configs:
      - targets: ['ephemeris:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    # Add labels for service identification
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'ephemeris-server'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'calculation_.*'
        target_label: component
        replacement: 'calculations'

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 30s

  # Node exporter for system metrics (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://cosmichub.com/health
        - https://cosmichub.com/api/health
        - https://cosmichub.com/api/ephemeris/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 10GB

# Remote write configuration (for long-term storage if needed)
# remote_write:
#   - url: "https://your-long-term-storage-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"
