#!/bin/bash
# AI Agent Coordination Cleanup Script
# Removes duplicate and inconsistently named files

cd /Users/Chris/Projects/CosmicHub/ai-agent-coordination

echo "🧹 Cleaning up AI agent coordination files..."

# Remove duplicate analysis files
echo "Removing duplicate analysis files..."
rm -f *-current-analysis.json
rm -f *-analysis-post-fix.json
rm -f *-fixes.json

# Remove any temporary or status files
echo "Removing temporary status files..."
rm -f *-status.json

# Keep only the core files for each agent:
# - agent-X-instructions.md (generated by coordination system)
# - agent-X-analysis.json (generated by coordination system)  
# - agent-X-completion.json (created by agents when done)

echo "📁 Remaining files:"
ls -la *.json *.md | grep -E "(instructions\.md|analysis\.json|completion\.json|coordination-manifest\.json)"

echo ""
echo "✅ Cleanup complete!"
echo "📋 Standard file structure:"
echo "   - agent-X-instructions.md (mission brief)"
echo "   - agent-X-analysis.json (current lint status)"
echo "   - agent-X-completion.json (results when done)"
echo "   - coordination-manifest.json (global coordination)"
echo ""
echo "🚫 Removed duplicates and temporary files"
echo "   - *-current-analysis.json"
echo "   - *-analysis-post-fix.json" 
echo "   - *-fixes.json"
echo "   - *-status.json"
