name: Type Check

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**/*.py'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**/*.py'

jobs:
  typecheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run mypy type checking
      working-directory: ./backend
      run: |
        # Run strict checking on well-typed files
        mypy --follow-imports=silent --ignore-missing-imports \
             --disallow-untyped-defs --disallow-incomplete-defs \
             --check-untyped-defs --pretty --show-error-codes \
             security/advanced_validation.py
        
        # Run basic checking on all files (non-blocking for now)
        mypy --follow-imports=silent --ignore-missing-imports \
             --pretty --show-error-codes security/ || true
